/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      G:/TI/Grace/grace/grace_2_20_02_32/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
#include <stdint.h>
#include "Display.h"
#include  "Buttons.h"
#include "main.h"

uint8_t pressedKey = NO_BUTTON;
extern uint8_t sleepLevel;
extern uint16_t gameDelayMs;
uint32_t ms = 0;

/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}


/* Interrupt Function Prototypes */




/*
 *  ======== PORT1 Interrupt Service Routine ========
 *
 * Here are several important notes on using PORTx interrupt Handler:
 *
 * 1. User must explicitly clear the port interrupt flag before exiting
 *
 *    PxIFG &= ~(BITy);
 *
 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=PORT1_VECTOR
__interrupt void PORT1_ISR_HOOK(void)
{
    /* USER CODE START (section: PORT1_ISR_HOOK) */
    if( P1IFG & (1 << 5))
    {
        // BUTTON 1
        pressedKey = BUTTON_1;
    }
   P1IFG = 0;
   if(sleepLevel > 0)
   {
   // any button will wake this up
   __bic_SR_register_on_exit(LPM0_bits); // Exit LPM0 on exiting ISR.
   }
    /* USER CODE END (section: PORT1_ISR_HOOK) */
}

/*
 *  ======== PORT2 Interrupt Service Routine ========
 *
 * Here are several important notes on using PORTx interrupt Handler:
 *
 * 1. User must explicitly clear the port interrupt flag before exiting
 *
 *    PxIFG &= ~(BITy);
 *
 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 *
 */
#pragma vector=PORT2_VECTOR
__interrupt void PORT2_ISR_HOOK(void)
{
    /* USER CODE START (section: PORT2_ISR_HOOK) */
    if( P2IFG & (1 << 0) )
    {
        // BUTTON 2
        P2IFG &= ~BIT0;
        pressedKey = BUTTON_2;
    }
    if( P2IFG & (1 << 1) )
    {
        // BUTTON 3
        P2IFG &= ~BIT1;
        pressedKey = BUTTON_3;
    }
    if( P2IFG & (1 << 2) )
    {
        // BUTTON 4
        P2IFG &= ~BIT2;
        pressedKey = BUTTON_4;
    }
    if(sleepLevel > 0)
    {
    // any button will wake this up
    __bic_SR_register_on_exit(LPM0_bits); // Exit LPM0 on exiting ISR.
    }
    //while(now <= gameDelayMs); // debouncen odottelua

    /* USER CODE END (section: PORT2_ISR_HOOK) */
}

/*
 *  ======== ADC10 Interrupt Service Routine ========
 */
#pragma vector=ADC10_VECTOR
__interrupt void ADC10_ISR_HOOK(void)
{
    /* USER CODE START (section: ADC10_ISR_HOOK) */
    __bic_SR_register_on_exit(LPM0_bits); // Exit LPM0 on exiting ISR.
    /* USER CODE END (section: ADC10_ISR_HOOK) */
}


/*
 *  ======== Timer1_A3 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER1_A0_VECTOR
__interrupt void TIMER1_A0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER1_A0_ISR_HOOK) */
    // Should be 1 ms clocks
    ms++;
    if(gameDelayMs > 0)
    {
        gameDelayMs--;
    }
    TA1CTL &= ~TAIFG; // clear flag
    if(sleepLevel > 0)
    {
        __bic_SR_register_on_exit(LPM0_bits); // Exit LPM0 on exiting ISR.
    }

    /* USER CODE END (section: TIMER1_A0_ISR_HOOK) */
}


/*
 *  ======== Watchdog Timer Interval Interrupt Handler Generation ========
 */
#pragma vector=WDT_VECTOR
__interrupt void WDT_ISR_HOOK(void)
{
    /* USER CODE START (section: WDT_ISR_HOOK) */
    // WDT triggers every 42 ms
    //updateDisplay();

    /* USER CODE END (section: WDT_ISR_HOOK) */
}
